const projects = [
    {
        id: 0,
        name: '🛍️ Fake Store',
        desc: 'A front-end application that uses mock-data from fakestoreapi.com',
        tech: ['frontend', 'vue', 'api'],
        rating: 4.3,
        image: 'img/fake-store.png',
        link: 'https://saacostam.github.io/fake-store/#/explore',
        category: 'dev',
    },
    {
        id: 1,
        name: '👾 Tetris',
        desc: 'A Tetris clone built using Vue',
        tech: ['game', 'frontend', 'vue'],
        rating: 3.3,
        image: 'img/tetris.png',
        link: '/vanilla-js-tetris',
        category: 'game'
    },
    {
        id: 2,
        name: '🎹 Piano Roll',
        desc: 'A functional Piano Roll for web music prototyping',
        tech: ['frontend', 'vue'],
        rating: 4.0,
        image: 'img/piano-roll.png',
        link: '/piano-roll',
        category: 'music'
    },
    {
        id:3,
        name: 'Random Maze Generator 🕹',
        desc: 'A game with randomly generated mazes and path validation',
        tech: ['game', 'frontend', 'vue', 'algorithms'],
        rating: 2.2,
        image: 'img/random-maze-generator.png',
        link: '/random-maze-generator',
        category: 'game'
    },
    {
        id:4,
        name: '🐧 Slippery Slope',
        desc: 'A platform game built using the Canvas element',
        tech: ['game', 'frontend', 'canvas'],
        rating: 3.6,
        image: 'img/slippery-slope.png',
        link: '/slippery-slope',
        category: 'game'
    },
    {
        id:5,
        name: '🧠 mem',
        desc: 'A card-based studying application for students',
        tech: ['frontend', 'vue', 'backend', 'nodejs', 'mongodb'],
        rating: 4.2,
        image: 'img/mem.png',
        link: 'https://mem.onrender.com/#/login',
        category: 'dev',
    },
    {
        id:6,
        name: '🎵 TuneCode',
        desc: 'A web based programming language and IDE',
        tech: ['frontend', 'vue', 'antlr', 'audio API'],
        rating: 4.6,
        image: 'img/tunecode.png',
        link: '/tune-code',
        category: 'music'
    },
    {
        id:7,
        name : '🚀 3D Music Visualizer',
        desc : 'A 3D music visualizer that uses audio API analysis and p5.js with WEBGL',
        tech : ['frontend', 'audio API', 'WEBGL', 'p5.js'],
        rating : 4.0,
        image: 'img/3dmusicvisualizer.png',
        link: '/3d-music-visualizer/',
        category: 'music',
    },
    {
        id:8,
        name : '✍ Sudoku',
        desc : 'A sudoku game built using the Canvas element',
        tech : ['game', 'frontend', 'canvas'],
        rating : 2.5,
        image: 'img/sudoku.png',
        link: '/sudoku',
        category: 'game',
    },
    {
        id: 9,
        name : '🖼 Music Visualizer',
        desc : 'A 3-band frequency-based visualizer that uses uses audio API analysis.',
        tech : ['frontend', 'audio API', 'canvas'],
        rating: 3.5,
        image : 'img/musicvisualizer.png',
        link : '/music-visualizer',
        category: 'music',
    },
    {
        id: 10,
        name : '🩺 Medirec',
        desc : 'Application that keeps track of medical files and shares them with doctors',
        tech : ['frontend', 'vue', 'api'],
        rating: 3.9,
        image : 'img/medirec.png',
        link : '/medirec',
        category: 'dev',
    },
    {
        id: 11,
        name : '🎵 Lalu',
        desc : 'Spotify-like application for music streaming',
        tech : ['frontend', 'vue', 'audio'],
        rating: 4.4,
        image : 'img/lalu.png',
        link : '/lalu',
        category: 'dev',
    },
    {
        id: 12,
        name : '🔌 Signal Grid',
        desc : 'Game similar to classic piping puzzles',
        tech : ['frontend', 'canvas', 'game'],
        rating: 2.4,
        image : 'img/signal-grid.png',
        link : 'https://saacostam.github.io/static-websites/signal-grid/',
        category: 'game',
    },
    {
        id: 13,
        name : '🧮 PI with Montecarlo Method',
        desc : 'Calculating PI with Montecarlo Method',
        tech : ['frontend', 'canvas', 'math'],
        rating: 1.0,
        image : 'img/montecarlo-pi.png',
        link : '/montecarlo-circle',
        category: 'dev',
    }
]

export default projects;
